### ISSUE TITLE
Error occurred after updating 3.9

### ISSUE THREAD

**Issue by Ciscodefran** [nuxt/test-utils#681] opened 2023-12-28 05:16 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.18.0`
- Nuxt Version:     `3.9.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `bun@1.0.20`
- Builder:          `-`
- User Config:      `devtools`, `modules`, `primevue`, `css`, `components`, `imports`, `i18n`, `supabase`, `runtimeConfig`, `experimental`, `vite`, `testUtils`
- Runtime Modules:  `@vueuse/nuxt@10.7.1`, `@nuxtjs/supabase@1.1.4`, `@nuxtjs/eslint-module@4.1.0`, `@nuxtjs/i18n@8.0.0-rc.5`, `@nuxtjs/stylelint-module@5.1.0`, `@pinia/nuxt@0.5.1`, `@pinia-plugin-persistedstate/nuxt@1.2.0`, `@element-plus/nuxt@1.0.7`, `nuxt-icon@0.6.8`, `@samk-dev/nuxt-vcalendar@1.0.2`, `@nuxt/image@1.1.0`, `nuxt-primevue@0.2.2`, `dayjs-nuxt@2.1.9`, `@nuxt/test-utils/module@3.9.0`
- Build Modules:    `-`

### Reproduction

update the package to 3.9.0. and put '@nuxt/test-utils/module' into modules in nuxt.config.
then in some reasons, it goes error when nuxt modules trying to import explicitly from #imports or #build.

### Describe the bug

I just updated test-utils as nuxt-vitest archived, and set config like you mentioned.
and running nuxt, it goes error.

### Logs

```shell-script
Could not resolve "#imports"

    node_modules/@nuxt/test-utils/dist/runtime-utils/index.mjs:5:46:
      5 │ import { defineComponent, useRouter, h } from '#imports';
        ╵                                               ~~~~~~~~~~

  You can mark the path "#imports" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "#build/root-component.mjs"

    node_modules/@nuxt/test-utils/dist/runtime-utils/index.mjs:6:21:
      6 │ import NuxtRoot from '#build/root-component.mjs';
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "#build/root-component.mjs" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.
-------------------------------------------
error while updating dependencies:                                                            2:11:00 PM
Error: Build failed with 2 errors:
node_modules/@nuxt/test-utils/dist/runtime-utils/index.mjs:5:46: ERROR: Could not resolve "#imports"
node_modules/@nuxt/test-utils/dist/runtime-utils/index.mjs:6:21: ERROR: Could not resolve "#build/root-component.mjs"
```

**Comment by AlbertBrand** [comment] 2023-12-29 14:01
Currently facing the same issue. The workaround I found is to remove the `"@nuxt/test-utils/module"` module from `nuxt.config.ts`. This removes the Vitest UI from the Nuxt devtools and does not affect testing from the console.

It seems that the module plugin tries to follow imports, however it does not understand the virtual `#imports` and others. This might be a timing thing? I'm sure @danielroe has a better understanding.

**Comment by rafaelmagalhaes** [comment] 2024-01-09 11:09
currently started facing the same issue, removing it from nuxt.config helped

**Comment by Ciscodefran** [comment] 2024-01-10 23:55
@rafaelmagalhaes But the problem is that when running a test, it fails to load #imports from in @nuxt/test-utils/dist/runtime-utils/index.js.

**Comment by AlbertBrand** [comment] 2024-01-11 12:52
I'll create a reproduction repo tomorrow. I think this has to do with test code in a project importing test-utils code.

**Comment by AlbertBrand** [comment] 2024-01-12 10:58
Finally got it reproduced here: https://stackblitz.com/edit/github-3etpwp?file=nuxt.config.ts,pages%2Fapp.nuxt.spec.ts

I could not get it to trigger first, but then I noticed that I had a test in the `pages` folder that called `mockNuxtImport` with `useRoute`. And that triggers the behavior. **If the test is outside the `pages` folder the @nuxt/test-utils module runs fine at startup.**

Could it be that the the Nuxt import mocking messes with the generated vue-router code? Seems like an order thing.

**Comment by danielroe** [comment] 2024-01-28 11:56
This should now be resolved via https://github.com/nuxt/test-utils/pull/726.

**Closed by danielroe** 2024-01-28 11:56 UTC
Labels: pending triage

**Comment by AlbertBrand** [comment] 2024-01-29 09:31
Just tested this on the test repo I created. The above error is now gone when running the tests, however a new error pops up when starting the project:

https://stackblitz.com/edit/github-3etpwp?file=package.json

```
 ERROR  This module cannot be imported in the Vue part of your app. [importing @nuxt/test-utils/runtime from pages/app.nuxt.spec.ts]
```

The error does not seem to have effect on the app startup itself (it's probably more a warning).

Again this error goes away when moving the test out of the `pages` folder.

@danielroe Should I create a new issue or do you want to reopen this one?

**Comment by danielroe** [comment] 2024-01-29 16:39
Do open a new issue 🙏 

We can probably resolve this easily.

**Comment by Ciscodefran** [comment] 2024-01-30 00:16
@AlbertBrand Same issue here :(

**Comment by AlbertBrand** [comment] 2024-01-30 09:28
Created https://github.com/nuxt/test-utils/issues/747

**Comment by muffincode** [comment] 2024-03-22 14:08
I'm still experiencing the issue mentionned on Jan 12, with
"@nuxt/test-utils": "3.12.0",
and "@nuxtjs/tailwindcss": "^6.11.4"

I tried what's mentionned [here](https://github.com/nuxt/nuxt/issues/20404) but it doesn't do the trick

I'll try to create a reproduction

**Comment by rafadpedrosa** [comment] 2024-04-21 03:00
I guys, I was having the same error, so, I tried a different approach and it worked for me. 

Well, it's a workaround - I think - but maybe it can help anyone who needs. Try to use **pnpm** instead.

my gitlab-ci

`
image: node:lts

stages:
  - test
  - deploy
  - rollback

# **MY CHANGES** Functions that should be executed before the build script is run
before_script:
  - npm -g install pnpm
  - pnpm install

test-unit:
  stage: test
  script:
    - pnpm run test

pages:
  stage: deploy
  script:
    - pnpm run generate
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - .output/public
  publish: .output/public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
`

**Comment by BBoehm** [comment] 2024-08-02 12:51
Was also still occuring here with version 3.13.1, seems to be gone in version 3.14.0
