### ISSUE TITLE
Documentation example for "Testing in a Browser" doesn't work, instead get ERR_LOAD_URL

### ISSUE THREAD

**Issue by remiconnesson** [nuxt/test-utils#983] opened 2024-10-17 12:09 UTC
### Environment

Using pnpm and following the steps from the [documentation](https://nuxt.com/docs/getting-started/testing#testing-in-a-browser) lead to an error that I wasn't able to fix on my own.

```
Error: Failed to load url /home/remi/work/spice/app/ui/node_modules/.pnpm/@nuxt+test-utils@3.14.3_@playwright+test@1.48.1_@vue+test-utils@2.4.6_h3@1.13.0_happy-dom@14._nwi3s52kfwvglwl5pg2z7gqeby/node_modules/@nuxt/test-utils/dist/shared/runtime/global-setup (resolved id: /home/remi/work/spice/app/ui/node_modules/.pnpm/@nuxt+test-utils@3.14.3_@playwright+test@1.48.1_@vue+test-utils@2.4.6_h3@1.13.0_happy-dom@14._nwi3s52kfwvglwl5pg2z7gqeby/node_modules/@nuxt/test-utils/dist/shared/runtime/global-setup). Does the file exist?
 ❯ loadAndTransform node_modules/.pnpm/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:51858:17

```

### Reproduction

(will do later)

### Describe the bug

Following documentation is not enough to get e2e with playwright testing to work.

**Comment by strokirk** [comment] 2024-10-19 11:01
Looks to be the same as https://github.com/nuxt/test-utils/issues/818?

**Comment by adamdehaven** [comment] 2024-11-29 16:37
Browser testing via `@playwright/test` works for me; if you can provide a reproduction I can take a look at what you're missing. (I'm assuming you're wanting to run tests via the Playwright Test Runner?)

**Comment by danielroe** [comment] 2024-12-05 06:41
resolved in https://github.com/nuxt/test-utils/commit/094acb299cc95c42154757bd0687806984e5ded0

**Closed by danielroe** 2024-12-05 06:41 UTC
Labels: needs reproduction
